### ISSUE TITLE
repo name != composer package name

### ISSUE THREAD

**Issue by spekulatius** [pcsg/pcsg-makerlog-php-client#1]
Hey @dehenne 

thanks for providing this lib! I'm implementing it atm in a project. I'll let you know once its done :) 

I noticed the composer name and the name github repo are different - that breaks the flow for lazy people like me to simply copy the URL bar quickly. Just letting you know.

Peter

**Comment by dehenne** [comment]
Hey @spekulatius,

thanks for your issue. and I am happy that you want to use the client. if your project is finished write me via twitter and send me the link! :-) . I would be very happy about it.

to the problem, :thinking: 

that's half right. the problem is, this repo is more a copy / clone / backup from https://dev.quiqqer.com/pcsg/makerlog-php-client. you can read more about the why here: https://github.com/pcsg/pcsg-makerlog-php-client#contribute

i don't know if this is so easy to change, since we have about 100 repos and 90% are adjusted here on github, we unfortunately had to go this way.
it's just an automated comparison. gitlab owns several groups and we had to map that somehow.

I don't think that's possible :(
sorry for that

**Comment by spekulatius** [comment]
Hey @dehenne 

thats fine - its not a major issue. Just a thing I noticed. 👍

Peter
